# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Todoey' do

  # Pods for Todoey

pod 'RealmSwift', '~> 3.17', :modular_headers => true
pod 'Realm', '~> 3.17', :modular_headers => true
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift',:git => 'https://github.com/ViccAlexander/Chameleon.git'

end
